spring.application.name=vn

spring.datasource.url=jdbc:postgresql://localhost:5432/vn_db
spring.datasource.username=vn_user
spring.datasource.password=vn_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=bXktc3VwZXItc2VjcmV0LWZvci12bi1wcm9qZWN0LTIwMjYtc2VjcmV0
app.jwt.access-expiration=86400000
app.jwt.refresh-expiration=604800000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.show-actuator=false
