apiVersion: v1
kind: Secret
metadata:
  name: vn-secret
  namespace: vn
type: Opaque
stringData:
  jwt-secret: "eygCyeoyb7lDqxFLh+175sIwTHEYvn4FCv2sJcnrDtBSPhJLU247E7JdgytL95pb7zygbfIbk19Nji3J5VZ+Mw=="
  db-password: "vn"
