apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vn-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ha1999/vn.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: vn

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
